create table public.expenses (
    id bigint generated by default as identity primary key,
    person text not null,
    description text not null,
    amount numeric not null,
    expense_date date not null,
    settled boolean not null default false
);

create table public.settlements (
    id bigint generated by default as identity primary key,
    settlement_date date not null,
    total numeric not null,
    mehrshad_paid numeric not null,
    shaghayegh_paid numeric not null,
    share_per_person numeric not null,
    debt_text text not null
);